---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: {{ template "efk.fullname" . }}-fluentd-es-v2.0.2
  labels:
    k8s-app: fluentd-es
    version: v2.0.2
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-es
      version: v2.0.2
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        k8s-app: fluentd-es
        kubernetes.io/cluster-service: "true"
        version: v2.0.2
        release: {{ .Release.Name }}
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
        - name: fluentd-es
          image: gcr.io/google-containers/fluentd-elasticsearch:v2.0.2
          env:
            - name: FLUENTD_ARGS
              value: --no-supervisor -q
          resources:
            limits:
              memory: {{ .Values.fluentd.containers.resources.limits.memory }}
            requests:
              cpu: {{ .Values.fluentd.containers.resources.requests.cpu }}
              memory: {{ .Values.fluentd.containers.resources.requests.memory }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: libsystemddir
              mountPath: /host/lib
              readOnly: true
            - name: config-volume
              mountPath: /etc/fluent/config.d
      nodeSelector:
        beta.kubernetes.io/fluentd-ds-ready: "true"
      terminationGracePeriodSeconds: {{ .Values.fluentd.terminationGracePeriodSeconds }}
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        # It is needed to copy systemd library to decompress journals
        - name: libsystemddir
          hostPath:
            path: /usr/lib64
        - name: config-volume
          configMap:
            name: {{ template "efk.fullname" . }}-fluentd-es-config-v0.1.1
