---
- name: Prepare app instance image
  hosts: all
  become: true
  vars:
    ubuntu_release: xenial
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install packages required to install Docker from repository
      apt: name={{ item }} state=present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ubuntu_release }} stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
