global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#georgy_vashchenko'
