#######################################################################
#                       Application services
#######################################################################
version: '3.3'
services:
# ---------------------------------------------------------- db
  post_db:
    image: mongo:${VERSION_MONGO:-latest}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db

# ---------------------------------------------------------- ui
  ui:
    image: ${USER_NAME}/ui:${VERSION_UI:-latest}
    ports:
      - ${UI_PORT:-9292}:${PUMA_PORT:-9292}/tcp
    networks:
      - front_net

# ---------------------------------------------------------- post
  post:
    image: ${USER_NAME}/post:${VERSION_POST:-latest}
    networks:
      - front_net
      - back_net

# ---------------------------------------------------------- comment
  comment:
    image: ${USER_NAME}/comment:${VERSION_COMMENT:-latest}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
