version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO:-latest}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db

  ui:
    build: ../src/ui
    image: ${USERNAME}/ui:${VERSION_UI:-latest}
    ports:
      - ${UI_PORT:-9292}:${PUMA_PORT:-9292}/tcp
    networks:
      - front_net

  post:
    build: ../src/post-py
    image: ${USERNAME}/post:${VERSION_POST:-latest}
    networks:
      - front_net
      - back_net

  comment:
    build: ../src/comment
    image: ${USERNAME}/comment:${VERSION_COMMENT:-latest}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
