version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO:-latest}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db

  ui:
    image: ${USERNAME}/ui:${VERSION_UI:-latest}
    ports:
      - ${UI_PORT:-9292}:${PUMA_PORT:-9292}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${VERSION_POST:-latest}
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME}/comment:${VERSION_COMMENT:-latest}
    networks:
      - front_net
      - back_net

  prometheus:
    image: ${USERNAME}/prometheus:${VERSION_PROMETHEUS:-latest}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net
volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
