---
- name: register runner
  shell:
    docker exec -it {{ container_name }} \
    gitlab-runner register \
    --non-interactive \
    --url "http://{{ public_ip }}" \
    --registration-token "{{ runner_token }}" \
    --description "{{ runner.description }}" \
    --tag-list "{{ runner.tags | join(',') }}" \
    --executor "{{ runner.executor }}" \
    --docker-image {{ runner.docker_image }} \
    --run-untagged \
    --locked=false
