---
global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'docker'
    static_configs:
      - targets:
          - 'dockerhost:9323'

  - job_name: 'ui'
    static_configs:
      - targets:
          - 'ui:9292'

  - job_name: 'comment'
    static_configs:
      - targets:
          - 'comment:9292'

  - job_name: 'post'
    static_configs:
      - targets:
          - 'post:5000'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'cadvisor:8080'

  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:9100'

  - job_name: 'mongodb'
    static_configs:
      - targets:
          - 'mongodb_exporter:9216'

  - job_name: blackbox # To get metrics about the exporter itself
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'blackbox_exporter:9115'

  - job_name: blackbox_services
    metrics_path: /probe
    params:
      module:
        - http_2xx
        - tcp_connect
    static_configs:
      - targets:
          - http://ui:9292
          - http://comment:9292
          - http://post:5000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: 'cloudprober'
    scrape_interval: 10s
    static_configs:
      - targets:
          - 'cloudprober:9313'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager:9093'
