version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO:-3.2}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSION_UI:-1.0}
    ports:
      - ${UI_PORT:-9292}:${PUMA_PORT:-9292}/tcp
    networks:
      - front_net

  post:
    build: ./post-py
    image: ${USERNAME}/post:${VERSION_POST:-1.0}
    networks:
      - front_net
      - back_net

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VERSION_COMMENT:-1.0}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
