---
user: docker-user
group: docker-user

docker_image: gitlab/gitlab-ce:latest
hostname: gitlab.example.com

runner:
  tags:
    - linux
    - xenial
    - ubuntu
    - docker
  docker_image: "docker:stable"
  executor: docker
  description: docker-runner
